easy_admin:
    site_name: 'Mon Curriculum Vitae'
    formats:
      date: 'd/m/Y'
      time: 'H:i'
      datetime: 'd/m/Y H:i:s'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'

    entities:
        # List the entity class name you want to manage
        Competences:
            class: App\Entity\Competences
            list:
                fields:
                   - { property: 'id'}
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Compt_images%' }
            # ...
            show:
                fields:
                   - { property: 'id'}
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Compt_images%' }
            form:
                fields:
                   - { property: 'Titre' }
                   - { property: 'imageFile', type: 'file' }
        # List the entity class name you want to manage        
        Hobbies:
            class: App\Entity\Hobbies
            list:
                fields:
                   - { property: 'id'}
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Hobb_images%' }

            show:
                fields:
                   - { property: 'id'}
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Hobb_images%' }
            form:
                fields:
                   - { property: 'Titre' }
                   - { property: 'imageFile', type: 'file' }
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'Titre' }
                    - { property: 'Poster', type: 'image', base_path: '%app.path.Article_images%' }
                    - { property: 'Article' }
                    - { property: 'Auteur' }
                    - { property: 'Publication' }
            
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'Titre' }
                    - { property: 'Poster', type: 'image', base_path: '%app.path.Article_images%' }
                    - { property: 'Article' }
                    - { property: 'Auteur' }
                    - { property: 'Publication' }
            form:
                fields:
                    - { property: 'Titre' }
                    - { property: 'imageFile', type: 'file', base_path: '%app.path.Article_images%' }
                    - { property: 'Article' }
                    - { property: 'Auteur' }
                    - { property: 'Publication' }
        # List the entity class name you want to manage
        Formation:
            class: App\Entity\Formation
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'Date' }
                    - { property: 'Diplome' }
                    - { property: 'Ecole' }
            
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'Date' }
                    - { property: 'Diplome' }
                    - { property: 'Ecole' }
            form:
                fields:
                    - { property: 'Date' }
                    - { property: 'Diplome' }
                    - { property: 'Ecole' }

        # List the entity class name you want to manage
        Experience:
            class: App\Entity\Experience
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'Date' }
                    - { property: 'Poste' }
                    - { property: 'Structure' }
            
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'Date' }
                    - { property: 'Poste' }
                    - { property: 'Structure' }
            form:
                fields:
                    - { property: 'Date' }
                    - { property: 'Poste' }
                    - { property: 'Structure' }

        # List the entity class name you want to manage
        Contact:
            class: App\Entity\Contact
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'Telephone' }
                    - { property: 'Email' }
                    - { property: 'Facebook', type: 'image' }
                    - { property: 'Twitter' }
                    - { property: 'Linkedin' }
                    - { property: 'Github' }
            
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'Telephone' }
                    - { property: 'Email' }
                    - { property: 'Facebook', type: 'image' }
                    - { property: 'Twitter' }
                    - { property: 'Linkedin' }
                    - { property: 'Github' }
            form:
                fields:
                    - { property: 'Telephone' }
                    - { property: 'Email' }
                    - { property: 'Facebook' }
                    - { property: 'Twitter' }
                    - { property: 'Linkedin' }
                    - { property: 'Github' }
