easy_admin:
    entities:
        # List the entity class name you want to manage
        Competences:
            class: App\Entity\Competences
            list:
                fields:
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Compt_images%' }
            # ...
            show:
                fields:
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Compt_images%' }
            form:
                fields:
                   - { property: 'Titre' }
                   - { property: 'imageFile', type: 'file' }
        
        Hobbies:
            class: App\Entity\Hobbies
            list:
                fields:
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Hobb_images%' }

            show:
                fields:
                   - { property: 'Titre' }
                   - { property: 'Image', type: 'image', base_path: '%app.path.Hobb_images%' }
            form:
                fields:
                   - { property: 'Titre' }
                   - { property: 'imageFile', type: 'file' }
