vich_uploader:
    db_driver: orm

    mappings:
        Compt_images:
            uri_prefix: '%app.path.Compt_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.Compt_images%'
